### ISSUE TITLE
Work on packaging the nnunetv2 version

### ISSUE THREAD

**Issue by euroso97** [georgeaidinis/DLICV#3]
```[tasklist]
### Tasks
- [x] finalize the inference
- [x] turn the v2 inference code into PyPi compatible format
- [x] enable pip install from GitHub repo
- [x] upload to PyPi
- [x] Test the installation from PyPi using pip install
```

**Comment by spirosmaggioros** [comment]
Commit [a8d49eb](https://github.com/CBICA/DLICV/commit/a8d49eb0f5647481f76690f53f6e20bc12bf4c04)[a8d49eb](https://github.com/CBICA/DLICV/commit/a8d49eb0f5647481f76690f53f6e20bc12bf4c04) checked the first 3, in order to check the last 2 we need to add the API to secerets, i will then close this issue with one linked PR

**Comment by spirosmaggioros** [comment]
This is closed as of the latest commit and merged into main
